export interface SausageApiError {
  error: {
    code: string;
    message: string;
    details?: unknown;
  };
}

export const SAUSAGE_ERROR_CODES = {
  VALIDATION_ERROR: 'SAUSAGE_VALIDATION_ERROR',
  NOT_FOUND: 'SAUSAGE_NOT_FOUND',
  FORBIDDEN_TRANSITION: 'SAUSAGE_FORBIDDEN_TRANSITION',
  INSUFFICIENT_STOCK: 'SAUSAGE_INSUFFICIENT_STOCK',
  NEGATIVE_STOCK_FORBIDDEN: 'SAUSAGE_NEGATIVE_STOCK_FORBIDDEN',
  RELEASE_QTY_INVALID: 'SAUSAGE_RELEASE_QTY_INVALID',
  NAMESPACE_VIOLATION: 'SAUSAGE_NAMESPACE_VIOLATION',
  INVALID_ORDER_STATUS: 'SAUSAGE_INVALID_ORDER_STATUS'
} as const;
